---
abstract: 'Client and Parser of content from the Wiktionary API'
author:
  - 'Chris Becker <clbecker@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wiktionary-Parser
no_index:
  directory:
    - t
    - inc
requires:
  Carp::Always: 0
  File::Path: 0
  Locale::Codes::Language: 0
  MediaWiki::API: 0
  Text::Unidecode: 0
resources:
  homepage: https://github.com/clbecker/perl-wiktionary-parser/wiki
  license: http://dev.perl.org/licenses/
  repository: https://github.com/clbecker/perl-wiktionary-parser/
version: 0.09
